import { Product } from '../types';

export const INITIAL_PRODUCTS: Partial<Product>[] = [
  // MOBILES / COMM-LINKS
  {
    name: 'X-PHNX 15 PRO MAX',
    price: 139900,
    originalPrice: 159900,
    description: 'Titanium-forged communication array with advanced optics and orbital link capabilities.',
    category: 'Assets',
    image: 'https://images.unsplash.com/photo-1696446701796-da61225697cc?auto=format&fit=crop&q=80&w=1000',
    rating: 4.9,
    reviews: 12450,
    featured: true,
    stock: 50,
    highlights: ['Titanium Chassis', 'Thermal Loop Cooling', 'Quantum Processor'],
    specifications: { 'Processor': 'A17 Pro Custom', 'Display': '6.7" OLED 120Hz', 'Network': '6G Ready' }
  },
  {
    name: 'S-CORE 24 ULTRA',
    price: 124900,
    originalPrice: 134900,
    description: 'Ultra-spectrum device featuring neural-sync stylus and integrated crypto-safe storage.',
    category: 'Assets',
    image: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&q=80&w=1000',
    rating: 4.8,
    reviews: 8900,
    featured: false,
    stock: 75,
    highlights: ['Neural Stylus', '100x Scan Zoom', 'Armor Aluminum'],
    specifications: { 'Memory': '16GB LPDDR5X', 'Storage': '1TB NVMe', 'Camera': '200MP Vector' }
  },
  {
    name: 'PIXEL NEURAL 8',
    price: 75900,
    originalPrice: 82900,
    description: 'AI-first communication device with real-time translation and tensor-based optics.',
    category: 'Assets',
    image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=1000',
    rating: 4.7,
    reviews: 5600,
    stock: 100,
    highlights: ['Tensor G3', 'AI Magic Editor', 'Clear Calling'],
  },
  {
    name: 'MOTO-RAZR EDGE',
    price: 89900,
    originalPrice: 99900,
    description: 'Folding display module with ultra-thin form factor and edge-to-edge illumination.',
    category: 'Assets',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=1000',
    rating: 4.5,
    reviews: 3200,
    stock: 40,
    highlights: ['Foldable OLED', 'Snapdragon Gen 2', 'Peak Design'],
  },
  {
    name: 'Z-FOLD VECTOR',
    price: 154900,
    originalPrice: 174900,
    description: 'Large-scale foldable station for multitasking and immersive terminal access.',
    category: 'Assets',
    image: 'https://images.unsplash.com/photo-1583573636246-18cb2246697f?auto=format&fit=crop&q=80&w=1000',
    rating: 4.6,
    reviews: 1200,
    stock: 15,
    highlights: ['7.6" Inner Core', 'S-Link Support', 'IPX8 Waterproof'],
  },
  // SHOES / BOOTS - AT LEAST 10
  {
    name: 'GRAVITY-X TACTICAL BOOTS',
    price: 18500,
    originalPrice: 22000,
    description: 'Lightweight urban tactical footwear with magnetic grip and impact redirection tech.',
    category: 'Shoes',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=1000',
    rating: 4.7,
    reviews: 3500,
    featured: true,
    stock: 120,
    highlights: ['Impact Redirection', 'Quick-Lace System', 'Water-Resistant'],
  },
  {
    name: 'NEO-STRIKE SNEAKERS',
    price: 12500,
    originalPrice: 15000,
    description: 'High-speed urban movement assets with breathable vector mesh and neon-luminescent accents.',
    category: 'Shoes',
    image: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?auto=format&fit=crop&q=80&w=1000',
    rating: 4.6,
    reviews: 2100,
    featured: false,
    stock: 200,
    highlights: ['Vector Mesh', 'Neon Accents', 'Cloud-Sync Comfort'],
  },
  {
    name: 'QUANTUM RUNNER X1',
    price: 8900,
    originalPrice: 11000,
    description: 'Budget-friendly performance runners with aerogel cushioning and simplified design.',
    category: 'Shoes',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=1000',
    rating: 4.5,
    reviews: 1500,
    stock: 300,
    highlights: ['Aerogel Sole', 'Lightweight', 'Washable'],
  },
  {
    name: 'PUMA-TECH ORBIT',
    price: 14500,
    originalPrice: 16500,
    description: 'Classic athletic brand meets futuristic tech. Superior energy return for urban sprints.',
    category: 'Shoes',
    image: 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=1000',
    rating: 4.7,
    reviews: 4200,
    stock: 80,
    highlights: ['Energy Return', 'Classic Silhouette', 'Durable Gum'],
  },
  {
    name: 'RE-VOID SLIPSTREAM',
    price: 19900,
    originalPrice: 24000,
    description: 'Premium laceless footwear with voice-activated fit adjustment and climate control.',
    category: 'Shoes',
    image: 'https://images.unsplash.com/photo-1512374382149-4332c6c021f1?auto=format&fit=crop&q=80&w=1000',
    rating: 4.9,
    reviews: 800,
    stock: 45,
    highlights: ['Laceless Tech', 'Fit-Sync AI', 'Climate Control'],
  },
  {
    name: 'ASICS-GRID MASTER',
    price: 13200,
    originalPrice: 14500,
    description: 'Stability-focused trainers for multi-terrain traversal and heavy industrial usage.',
    category: 'Shoes',
    image: 'https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&q=80&w=1000',
    rating: 4.8,
    reviews: 3100,
    stock: 110,
    highlights: ['Stability Grid', 'Steel Toe Option', 'Anti-Slip'],
  },
  {
    name: 'JORDAN-CYBER 1',
    price: 28000,
    originalPrice: 35000,
    description: 'Iconic heritage meets cyber-streetwear. Limited edition vector-printed leather.',
    category: 'Shoes',
    image: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&q=80&w=1000',
    rating: 4.9,
    reviews: 12000,
    stock: 10,
    highlights: ['Limited Release', 'Heritage DNA', 'Vector Leather'],
  },
  {
    name: 'VANS-CORE SLIP',
    price: 6500,
    originalPrice: 7500,
    description: 'Simple, effective, and durable. The standard for urban skate and casual deployment.',
    category: 'Shoes',
    image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&q=80&w=1000',
    rating: 4.7,
    reviews: 9800,
    stock: 400,
    highlights: ['Waffle Grip', 'Durable Canvas', 'Quick On/Off'],
  },
  {
    name: 'TIMBER-TECH BOOT',
    price: 22500,
    originalPrice: 26000,
    description: 'Classic work boot redesigned with sensor-equipped soles for terrain mapping.',
    category: 'Shoes',
    image: 'https://images.unsplash.com/photo-1520639889313-751975e65cae?auto=format&fit=crop&q=80&w=1000',
    rating: 4.8,
    reviews: 2400,
    stock: 60,
    highlights: ['Waterproof', 'Terrain Mapping', 'Steel Shank'],
  },
  {
    name: 'ADIDAS-ULTRA NEON',
    price: 17800,
    originalPrice: 19500,
    description: 'Responsive boost technology with integrated light-strips for night-time visibility.',
    category: 'Shoes',
    image: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?auto=format&fit=crop&q=80&w=1000',
    rating: 4.7,
    reviews: 5800,
    stock: 150,
    highlights: ['Boost Midsole', 'Neon Light-Strips', 'Primeknit'],
  },
  {
    name: 'BALENCI-TECH SNEAKER',
    price: 85000,
    originalPrice: 95000,
    description: 'High-fashion technical footwear with multi-layered sole and distress-resistant mesh.',
    category: 'Shoes',
    image: 'https://images.unsplash.com/photo-1511556532299-8f662fc26c06?auto=format&fit=crop&q=80&w=1000',
    rating: 4.6,
    reviews: 1200,
    stock: 5,
    highlights: ['Designer DNA', 'Oversized Sole', 'Streetwear Ready'],
  },
  {
    name: 'CONVERSE-VECTOR CHUCK',
    price: 5500,
    originalPrice: 6200,
    description: 'The timeless classic updated with vector-weave stitching and reinforced eyelets.',
    category: 'Shoes',
    image: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&q=80&w=1000',
    rating: 4.8,
    reviews: 15000,
    stock: 500,
    highlights: ['Canvas Classic', 'Vector Stitching', 'Unisex Fit'],
  },
  {
    name: 'Essential Heather Tee',
    price: 2560,
    originalPrice: 3200,
    description: 'A premium, soft-touch heathered t-shirt crafted from a breathable cotton-poly blend for perfect daily comfort. Optimized for mission pairing with tactical shoes.',
    category: 'Shoes',
    image: 'https://framerusercontent.com/images/sAeo5d2sebZSKf6CN7HEtOtJ9k.mp4',
    rating: 4.8,
    reviews: 1240,
    featured: true,
    stock: 210,
    highlights: ['Breathable Cotton Blend', 'Minimalist Fit', 'Eco-dyed Fabric'],
  },
  {
    name: 'KILLER KL8040 Lightweight Casual Loafers',
    price: 749,
    originalPrice: 3499,
    description: 'Engineered for daily deployment. These lightweight shoe loafers feature advanced soft-cushion technology for maximum comfort during long-duration technical tasks.',
    category: 'Shoes',
    image: 'https://rukminim1.flixcart.com/image/1536/1536/xif0q/shoe/l/3/y/12-kl8040-olive-12-killer-olive-original-imahkkrrpgj5xemh.jpeg?q=90',
    rating: 3.9,
    reviews: 52845,
    featured: true,
    stock: 15,
    highlights: ['Soft Cushion Comfort', 'Lightweight Construction', 'Casual Deployment Ready'],
  },
  // ACCESSORIES
  {
    name: 'V-LINK HEADSET PRO',
    price: 25000,
    originalPrice: 32000,
    description: 'Studio-grade audio interface with neural noise cancellation and ultra-low latency wireless.',
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=1000',
    rating: 4.8,
    reviews: 4500,
    featured: true,
    stock: 300,
    highlights: ['Neural NC', '72hr Battery', 'Carbon Frame'],
  },
  {
    name: 'TEK-PACK MODULAR',
    price: 8500,
    originalPrice: 12000,
    description: 'Expandable storage solution with integrated USB-C charging and anti-theft RFID shielding.',
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=1000',
    rating: 4.7,
    reviews: 1800,
    featured: false,
    stock: 150,
    highlights: ['RFID Shield', 'Modular Straps', 'Battery Built-in'],
  },
  {
    name: 'G-LINK VR HUB',
    price: 54900,
    originalPrice: 65000,
    description: 'Stand-alone immersive terminal with spatial audio and 4K micro-OLED lenses.',
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?auto=format&fit=crop&q=80&w=1000',
    rating: 4.9,
    reviews: 2300,
    stock: 25,
    highlights: ['4K Per Eye', 'Hand Tracking', 'Wireless Hub'],
  },
  {
    name: 'KEY-BOARD PHANTOM',
    price: 12500,
    originalPrice: 15000,
    description: 'Mechanical input module with zero-latency switches and magnetic wrist-rest.',
    category: 'Accessories',
    image: 'https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&q=80&w=1000',
    rating: 4.8,
    reviews: 4100,
    stock: 120,
    highlights: ['Hall Effect Switches', 'Rapid Trigger', 'RGB Underglow'],
  },
  // WATCHES
  {
    name: 'CHRONOS-X TACTICAL',
    price: 45000,
    originalPrice: 55000,
    description: 'Ruggedized smart timepiece with bio-metric scanning, GPS mapping, and solar backup system.',
    category: 'Watches',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=1000',
    rating: 4.9,
    reviews: 3200,
    featured: true,
    stock: 45,
    highlights: ['Sapphire Glass', 'Solar Backup', 'Bio-Metrics'],
    specifications: { 'Glass': 'Sapphire Crystal', 'Case': 'Carbon Fiber', 'Waterproof': '10ATM' }
  },
  {
    name: 'ROLEX-CORE GMT',
    price: 950000,
    originalPrice: 1100000,
    description: 'The pinnacle of luxury horology. Re-engineered with ceramic bezel and 72-hour power reserve.',
    category: 'Watches',
    image: 'https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&q=80&w=1000',
    rating: 5.0,
    reviews: 450,
    stock: 2,
    highlights: ['Ceramic Bezel', '72h Reserve', '904L Steel'],
  },
  {
    name: 'CASIO-NEO G',
    price: 12500,
    originalPrice: 14000,
    description: 'Indestructible digital module with bluetooth-sync and neon backlight.',
    category: 'Watches',
    image: 'https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?auto=format&fit=crop&q=80&w=1000',
    rating: 4.8,
    reviews: 12000,
    stock: 200,
    highlights: ['Shock Resistant', 'Bluetooth Link', '200m WR'],
  },
  {
    name: 'Chilled Luxury Beverage Cooler',
    price: 14800,
    originalPrice: 18500,
    description: 'Premium beverage cooling system designed for optimal temperature. Features advanced thermal technology and minimalist aesthetics for the modern bar.',
    category: 'Assets',
    image: 'https://framerusercontent.com/images/bcpGrpWZOizFDiFHHCIQvJjZLNU.mp4',
    rating: 4.9,
    reviews: 86,
    featured: true,
    stock: 15,
    highlights: ['Advanced Thermal Tech', 'Minimalist Design', 'Energy Efficient', 'Quiet Operation'],
    specifications: { 'Capacity': '45 Liters', 'Cooling': 'Dual-Core Thermoelectric', 'Temp Range': '3°C - 18°C' },
    warranty: '2 Year Comprehensive Warranty',
    replacement: '10 Days Replacement',
    cod: true
  },
  {
    name: 'Interactive 3D Product Viewer',
    price: 39900,
    originalPrice: 49900,
    description: 'Custom high-fidelity 3D product visualization service. Includes interactive viewer integration for immersive e-commerce experiences.',
    category: 'Studio',
    image: 'https://framerusercontent.com/images/TPSEHRBNahpRHYLZ1SmKJ1p5rc.mp4',
    rating: 4.9,
    reviews: 24,
    featured: true,
    stock: 100,
    highlights: ['4K WebGL Rendering', 'AR Ready Assets', 'Cross-Platform Support', 'High Conversion Rates'],
    specifications: { 'Engine': 'WebGL 2.0', 'Resolution': 'Uncapped', 'Formats': 'GLB, GLTF' },
    warranty: 'Technical Support Included',
    replacement: 'Customized Service Policy',
    cod: false
  }
];
